### ISSUE TITLE
Add installation steps

### ISSUE THREAD

**Issue by imskr** [VaughnValle/elektropunk#3]
- How to install and achieve this on fresh base Arch Linux or Artix?

**Comment by VaughnValle** [comment]
Will work on the tutorial README and video soon :) Also, a user named lotation has been very kind to make an install script specifically for this rice, you can check it out here https://github.com/lotation/scripts/blob/archlinux/elektropunk-install.sh :)

**Comment by andrewpap22** [comment]
Hello there, 

Pretty cool rice, congratulations for the amazing work! 

The provided script is not working properly. 

Any updates on the installation for the particular rice?

**Comment by VaughnValle** [comment]
Will try to work on it soon, but I can't give a solid date as these are very difficult times in our country. As much as I wanted to, due to the circumstance it may take longer than usual sorry.

**Comment by andrewpap22** [comment]
No need to apologize at all. I will also try to make the above installation script work, and If I succeed I will post back here! I do face difficulties in my country as well, with all these fires expanding into more and more places! Stay strong!

**Comment by lotation** [comment]
> Hello there,
> 
> Pretty cool rice, congratulations for the amazing work!
> 
> The provided script is not working properly.
> 
> Any updates on the installation for the particular rice?

Sorry, I forgot to update the script, can you tell where it fails?

**Comment by andrewpap22** [comment]
Hello, @lotation 

On lines 167 to 171 you've forgotten a git diff there, 

```bash
<<<<<<< HEAD
		yay -S spotify --noconfirm --noprogressbar --skippgpcheck 1>/dev/null 2>>~/errors.log
=======
		yay -S spotify --noconfirm --noprogressbar --nopgpfetch 1>/dev/null 2>>~/errors.log
>>>>>>> bbcc7771341c2968d532085dc2d3d9b9e62be5c1
```

I don't remember which one i removed in the end but even still the script didn't complete successfully. 

I tried to use it on a fresh install of Artix Linux (runnit). 

Excuse me but I don't exactly remember now where exactly it failed, and I've not kept the logs as I've added myself stuff I needed for my Artix Installation. Maybe you want to try and run the script for a new user on your existing Artix Installation if you already have one? 

Else when I do find some free time (I'm super busy with work right now), I'll try to play with it a bit more and see what I can do about it and update you here! 

Have a good day!

**Comment by lotation** [comment]
Hey @andrewpap22 I accepted your Incoming Change and reviewed the whole script since has been a while.

As you can see from lines 199 and 200 I wrote it for Arch Linux, thus I had systemd in mind.

Anyway I suggest to use the script as reference to do the steps by yourself since many things have changed and will always change, maintaining a script like that consumes a lot of time.

Plus I ditched SLiM since it's discontinued and doesn't conform to the modern login manager requirements as you can see in the warning [here](https://wiki.archlinux.org/title/SLiM)

PS: I don't use this rice anymore and I'd need to set up a VM with Artix to test it but right now I'm pretty busy too. Tho, if you need help setting up anything PM [me](https://t.me/lotation) and I'll try to help
